import { Itemplo, cPlayers, emplo } from '../models/data';

export const cricketPlayers: Array<cPlayers> = [
  {
    name: 'Virat Kohli',
    country: 'India',
    role: 'Batsman',
    age: 33,
    matchesPlayed: 254,
    totalRuns: 12169,
    totalWickets: 4,
  },
  {
    name: 'Kane Williamson',
    country: 'New Zealand',
    role: 'Batsman',
    age: 31,
    matchesPlayed: 154,
    totalRuns: 7182,
    totalWickets: 29,
  },
  {
    name: 'Joe Root',
    country: 'England',
    role: 'Batsman',
    age: 31,
    matchesPlayed: 111,
    totalRuns: 9030,
    totalWickets: 36,
  },
  {
    name: 'Babar Azam',
    country: 'Pakistan',
    role: 'Batsman',
    age: 26,
    matchesPlayed: 81,
    totalRuns: 3808,
    totalWickets: 0,
  },
  {
    name: 'Steve Smith',
    country: 'Australia',
    role: 'Batsman',
    age: 32,
    matchesPlayed: 77,
    totalRuns: 7540,
    totalWickets: 17,
  },
  {
    name: 'Kagiso Rabada',
    country: 'South Africa',
    role: 'Bowler',
    age: 26,
    matchesPlayed: 47,
    totalRuns: 571,
    totalWickets: 213,
  },
  {
    name: 'Trent Boult',
    country: 'New Zealand',
    role: 'Bowler',
    age: 32,
    matchesPlayed: 79,
    totalRuns: 875,
    totalWickets: 317,
  },
  {
    name: 'Jasprit Bumrah',
    country: 'India',
    role: 'Bowler',
    age: 27,
    matchesPlayed: 19,
    totalRuns: 57,
    totalWickets: 83,
  },
  {
    name: 'Pat Cummins',
    country: 'Australia',
    role: 'Bowler',
    age: 28,
    matchesPlayed: 35,
    totalRuns: 493,
    totalWickets: 164,
  },
  {
    name: 'Rashid Khan',
    country: 'Afghanistan',
    role: 'Bowler',
    age: 23,
    matchesPlayed: 63,
    totalRuns: 658,
    totalWickets: 140,
  },
  {
    name: 'Ben Stokes',
    country: 'England',
    role: 'All-rounder',
    age: 29,
    matchesPlayed: 71,
    totalRuns: 4549,
    totalWickets: 161,
  },
  {
    name: 'Hardik Pandya',
    country: 'India',
    role: 'All-rounder',
    age: 27,
    matchesPlayed: 60,
    totalRuns: 1174,
    totalWickets: 54,
  },
  {
    name: 'Jason Holder',
    country: 'West Indies',
    role: 'All-rounder',
    age: 29,
    matchesPlayed: 49,
    totalRuns: 1987,
    totalWickets: 123,
  },
  {
    name: 'Mohammad Nabi',
    country: 'Afghanistan',
    role: 'All-rounder',
    age: 36,
    matchesPlayed: 128,
    totalRuns: 2683,
    totalWickets: 177,
  },
  {
    name: 'Quinton de Kock',
    country: 'South Africa',
    role: 'Wicketkeeper',
    age: 28,
    matchesPlayed: 53,
    totalRuns: 2958,
    totalWickets: 5,
  },
  {
    name: 'Jos Buttler',
    country: 'England',
    role: 'Wicketkeeper',
    age: 30,
    matchesPlayed: 91,
    totalRuns: 3022,
    totalWickets: 45,
  },
];

export const users: Array<emplo> = [
  {
    id: 101,
    name: 'john',
    city: 'DELHI',
    salary: 200000,
    dob: new Date('05/10/1989'),
  },

  {
    id: 102,
    name: 'peter',
    city: 'PUNE',
    salary: 8000,
    dob: new Date('05/12/1985'),
  },

  {
    id: 103,
    name: 'omed',
    city: 'GOA',
    salary: 198000,
    dob: new Date('10/10/1991'),
  },

  {
    id: 104,
    name: 'kunal',
    city: 'DELHI',
    salary: 55000,
    dob: new Date('12/18/1987'),
  },
];

export const employees: Array<Itemplo> = [
  {
    name: 'John Doe',
    gender: 'male',
    age: 25,
    department: 'Marketing',
    salary: 40000,
    yearsOfExperience: 3,
  },
  {
    name: 'Jane Smith',
    gender: 'female',
    age: 30,
    department: 'Sales',
    salary: 50000,
    yearsOfExperience: 5,
  },
  {
    name: 'Bob Johnson',
    gender: 'male',
    age: 40,
    department: 'Finance',
    salary: 70000,
    yearsOfExperience: 12,
  },
  {
    name: 'Sara Lee',
    gender: 'female',
    age: 28,
    department: 'HR',
    salary: 45000,
    yearsOfExperience: 4,
  },
  {
    name: 'Tom Jackson',
    gender: 'male',
    age: 35,
    department: 'IT',
    salary: 60000,
    yearsOfExperience: 8,
  },
  {
    name: 'Amy Chen',
    gender: 'female',
    age: 27,
    department: 'Marketing',
    salary: 42000,
    yearsOfExperience: 2,
  },
  {
    name: 'Mike Kim',
    gender: 'male',
    age: 45,
    department: 'Sales',
    salary: 80000,
    yearsOfExperience: 15,
  },
  {
    name: 'Grace Lee',
    gender: 'female',
    age: 32,
    department: 'Finance',
    salary: 55000,
    yearsOfExperience: 6,
  },
  {
    name: 'Eric Wong',
    gender: 'female',
    age: 29,
    department: 'HR',
    salary: 48000,
    yearsOfExperience: 3,
  },
  {
    name: 'Lucas Rodriguez',
    gender: 'male',
    age: 37,
    department: 'IT',
    salary: 65000,
    yearsOfExperience: 10,
  },
  {
    name: 'Karen Wilson',
    gender: 'male',
    age: 31,
    department: 'Marketing',
    salary: 42000,
    yearsOfExperience: 3,
  },
  {
    name: 'lucy Brown',
    gender: 'female',
    age: 43,
    department: 'Sales',
    salary: 75000,
    yearsOfExperience: 13,
  },
  {
    name: 'Anna Nguyen',
    gender: 'male',
    age: 26,
    department: 'Finance',
    salary: 50000,
    yearsOfExperience: 4,
  },
  {
    name: 'Paul Kim',
    gender: 'male',
    age: 28,
    department: 'HR',
    salary: 46000,
    yearsOfExperience: 2,
  },
  {
    name: 'july Lee',
    gender: 'female',
    age: 33,
    department: 'IT',
    salary: 62000,
    yearsOfExperience: 7,
  },
];
